# Project information
site_name: 大数据文档
site_url: https://doc.gump.cloud
site_author: Mr. Gump

theme:
  name: material
  custom_dir: .overrides
  icon:
    logo: material/database-outline
    repo: fontawesome/brands/git-alt 
  features:
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
extra:
  homepage: https://doc.gump.cloud
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Mr-Gump/bigdata_doc
plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - glightbox

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

repo_name: bigdata_doc
repo_url: https://github.com/Mr-Gump/bigdata_doc
copyright: Copyright &copy; 2022 - 2023 Mr. Gump

extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- js/termynal.js
- js/custom.js
- js/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Material: 
    - Home: index.md
    - 提示: mkdocs/admonitions.md
    - 按钮: mkdocs/buttons.md
    - 代码块: mkdocs/code-blocks.md
    - 内容标签页: mkdocs/content-tabs.md
    - 数据表格: mkdocs/data-tables.md
    - 图表: mkdocs/diagrams.md
    - 角注: mkdocs/footnotes.md
    - 格式: mkdocs/formatting.md
    - 网格: mkdocs/grids.md
    - 图标，表情: mkdocs/icons-emojis.md
    - 图像: mkdocs/images.md
    - 列表: mkdocs/lists.md
    - 工具提示: mkdocs/tooltips.md
    - MathJax: mkdocs/mathjax.md
    - Termynal: mkdocs/termynal.md
  - Scala: 
    - scala/index.md
  - Hadoop: 
    - Hadoop概述: hadoop/hdp_01.md
    - Hadoop运行环境搭建: hadoop/hdp_02.md
    - 常见错误及解决方案: hadoop/hdp_04.md
  - Zookeeper:
    - Zookeeper入门: zookeeper/zk_01.md
    - Zookeeper安装: zookeeper/zk_02.md
    - Zookeeper实战: zookeeper/zk_03.md
  - 消息队列: 
    - Kafka:
      - Kafka概述: mq/kafka/kf_01.md
      - Kafka快速入门: mq/kafka/kf_02.md
      - Kafka生产者: mq/kafka/kf_03.md
      - Kafka Broker工作流程: mq/kafka/kf_04.md
      - Kafka消费者: mq/kafka/kf_05.md
  - 计算引擎:
    - Spark: 
      - Spark概述: engine/spark/spark_01.md
      - Spark运行模式: engine/spark/spark_02.md
      - RDD概述: engine/spark/spark_03.md
      - RDD编程: engine/spark/spark_04.md
      - 累加器: engine/spark/spark_05.md
      - 广播变量: engine/spark/spark_06.md
      - SparkCore实战: engine/spark/spark_07.md
      - SparkSQL概述: engine/spark/spark_08.md
      - SparkSQL编程: engine/spark/spark_09.md
      - SparkSQL数据的加载与保存: engine/spark/spark_10.md
      - SparkSQL项目实战: engine/spark/spark_11.md
      - Spark提交流程: engine/spark/spark_12.md
      - Spark任务的执行: engine/spark/spark_13.md
      - Shuffle: engine/spark/spark_14.md
      - Spark内存管理: engine/spark/spark_15.md
      - SparkSQL优化: engine/spark/spark_16.md
    - Spark Streaming:
      - SparkStreaming概述: engine/spark_streaming/ss_01.md
      - HelloWorld: engine/spark_streaming/ss_02.md
      - DStream转换: engine/spark_streaming/ss_03.md
      - DStream输出: engine/spark_streaming/ss_04.md
      - 优雅关闭: engine/spark_streaming/ss_05.md
    - Flink: 
      - 初识 Flink: engine/flink/flink_01.md
      - Flink运行时架构: engine/flink/flink_02.md
      - DataStream API: engine/flink/flink_03.md
      - 底层API: engine/flink/flink_04.md
      - 窗口: engine/flink/flink_05.md
      - 逻辑时钟-水位线: engine/flink/flink_06.md
      - 多流合并: engine/flink/flink_07.md
      - Flink水位线机制: engine/flink/flink_watermark.md
    - Tez:
      - Tez概述: engine/tez/tez_01.md
      - Hive on Tez部署: engine/tez/tez_02.md
    - Hive: 
      - Hive入门: engine/hive/hive_01.md
      - Hive安装: engine/hive/hive_02.md
      - Hive数据类型: engine/hive/hive_03.md
      - DDL: engine/hive/hive_04.md
      - DML: engine/hive/hive_05.md
      - 查询: engine/hive/hive_06.md
      - 综合案例练习（初级）: engine/hive/hive_07.md
      - 函数: engine/hive/hive_08.md
      - 综合案例练习（中级）: engine/hive/hive_09.md
      - 分区表和分桶表: engine/hive/hive_10.md
      - 文件格式和压缩: engine/hive/hive_11.md
      - 企业级调优: engine/hive/hive_12.md
      - 综合案例练习（高级）: engine/hive/hive_13.md
      - 常见错误及解决方案: engine/hive/hive_14.md

  - 版本控制工具: 
    - 版本控制工具: vcs/index.md
    - Maven: vcs/maven.md
    - Git: vcs/git.md
  - 数据采集工具: 
    - 数据采集工具: sync/index.md
    - DataX: sync/datax.md
    - MaxWell: sync/maxwell.md
    - Flume: sync/flume.md
  - 调度工具:
    - 调度工具: schedule/index.md
    - Dophin Scheduler: schedule/ds.md
  - 数据库:
    - Redis: 
      - NoSQL: db/redis/rd_01.md
      - Redis简介: db/redis/rd_02.md
      - Redis安装: db/redis/rd_03.md
      - Redis的五大数据类型: db/redis/rd_04.md
      - Redis的相关配置: db/redis/rd_05.md
      - Jedis: db/redis/rd_06.md
      - Redis 持久化: db/redis/rd_07.md
    - Clickhouse: 
      - ClickHouse入门: db/ck/ck_01.md
      - ClickHouse安装: db/ck/ck_02.md
      - 数据类型: db/ck/ck_03.md
      - 表引擎: db/ck/ck_04.md
      - SQL操作: db/ck/ck_05.md
      - 副本: db/ck/ck_06.md
      - 分片集群: db/ck/ck_07.md
      - Bitmap: db/ck/ck_08.md
    - Hbase:
      - HBase简介: db/hbase/hb_01.md
      - HBase快速入门: db/hbase/hb_02.md
      - HBase API: db/hbase/hb_03.md
      - HBase进阶: db/hbase/hb_04.md
      - HBase优化: db/hbase/hb_05.md
      - 整合Phoenix: db/hbase/hb_06.md
  - 容器化:
    - docker: container/docker.md
    - kubernetes: container/k8s.md
  - 项目文档:
    - 数据仓库建模理论:
      - 数据仓库概述: project/dataware_01.md
      - 数据仓库建模概述: project/dataware_02.md
      - 维度建模理论之事实表: project/dataware_03.md
      - 维度建模理论之维度表: project/dataware_04.md
      - 数据仓库设计: project/dataware_05.md
  - 面试:
    - 字节跳动:
      - 面一: interview/zjtd/zj_01.md